# [toolchain]
# anchor_version = "0.29.0"
# solana_version = "1.16.9" # Solana version to use

[toolchain]
anchor_version = "0.28.0"

[features]
seeds = true

[registry]
url = "https://api.apr.dev"

[workspace]
members = [
    "programs/merkle-distributor",
]

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
merkle_distributor = "KdisqEcXbXKaTrBFqeDLhMmBvymLTwj9GmhDcdJyGat"

[programs.devnet]
merkle_distributor = "KdisqEcXbXKaTrBFqeDLhMmBvymLTwj9GmhDcdJyGat"

[programs.testnet]
merkle_distributor = "KdisqEcXbXKaTrBFqeDLhMmBvymLTwj9GmhDcdJyGat"

[programs.localnet]
merkle_distributor = "KdisqEcXbXKaTrBFqeDLhMmBvymLTwj9GmhDcdJyGat"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
