export { newDistributor } from "./newDistributor"
export type {
  NewDistributorArgs,
  NewDistributorAccounts,
} from "./newDistributor"
export { closeDistributor } from "./closeDistributor"
export type { CloseDistributorAccounts } from "./closeDistributor"
export { closeClaimStatus } from "./closeClaimStatus"
export type { CloseClaimStatusAccounts } from "./closeClaimStatus"
export { setEnableSlot } from "./setEnableSlot"
export type { SetEnableSlotArgs, SetEnableSlotAccounts } from "./setEnableSlot"
export { newClaim } from "./newClaim"
export type { NewClaimArgs, NewClaimAccounts } from "./newClaim"
export { claimLocked } from "./claimLocked"
export type { ClaimLockedAccounts } from "./claimLocked"
export { clawback } from "./clawback"
export type { ClawbackAccounts } from "./clawback"
export { setClawbackReceiver } from "./setClawbackReceiver"
export type { SetClawbackReceiverAccounts } from "./setClawbackReceiver"
export { setAdmin } from "./setAdmin"
export type { SetAdminAccounts } from "./setAdmin"
